# Generated by Django 5.0.4 on 2024-05-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordreset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordReset',
            new_name='ForgetPassword',
        ),
    ]
